services:
  hadoop:
    build: .
    hostname: hadoop
    ports:
      - "9870:9870" # HDFS Web UI
      - "8088:8088" # YARN Web UI
    volumes:
      - hadoop_data:/usr/local/hadoop/data
      - /c/Users/cb314/workspace/school/bigdata:/host_data
    networks:
      - hadoop_network

networks:
  hadoop_network:


volumes:
  hadoop_data:
